### ISSUE TITLE
ERROR: [youtube] : No video formats found!

### ISSUE THREAD

**Issue by ivoarch** [alexta69/metube#537]
Hi, I get this error every time I try to download video from Youtube .

My docker-compose.yml

```
services:
  metube:
    image: ghcr.io/alexta69/metube
    container_name: metube
    restart: unless-stopped
    ports:
      - "8081:8081"
    volumes:
      - "/mnt/pve/sb/downloads:/downloads:rw"
```

Is my first install and setup,

What I missing ?
Thanks!

**Comment by PikuZheng** [comment]
network issue i believe

**Comment by drabgaol** [comment]
I'm also having this issue, it seems to be cookies related? I was able to download 3 videos before this error showed up.
Is there any way to automatically update cookies?

**Comment by kmross** [comment]
Additionally I am also having this issue. This implementation has been going strong for several months now. Updated container and is still occurring.

**Comment by PikuZheng** [comment]
> I'm also having this issue, it seems to be cookies related? I was able to download 3 videos before this error showed up.
> Is there any way to automatically update cookies?

use cookiecloud maybe #418

**Comment by drabgaol** [comment]
> 
> use cookiecloud maybe #418

I use Firefox for my cookies so that's not going to work. Maybe this could be something to fix/implement in the next update, a way to automatically update the cookies from inside the MeTube container?

As it is right now MeTube is unusable to me seeing as I have to manually update the cookies every 5 minutes.

**Comment by PikuZheng** [comment]
> I use Firefox for my cookies so that's not going to work. Maybe this could be something to fix/implement in the next update, a way to automatically update the cookies from inside the MeTube container?
> 
> As it is right now MeTube is unusable to me seeing as I have to manually update the cookies every 5 minutes.

cookies from Firefox is not compatible for netscape. sorry.

**Comment by Nikita52NGG** [comment]
Я вас не знаю и в душе не ебу что происходит

ср, 13 нояб. 2024 г., 11:43 PikuZheng ***@***.***>:

**Comment by Kf637** [comment]
I've attempted to download over 10 videos without luck.

**Comment by Kf637** [comment]
````
DEBUG:ytdl:Processing as a video
INFO:ytdl:downloading youtube video #Af-vC8Q8M7c
INFO:aiohttp.access:172.18.0.1 [19/Nov/2024:10:00:22 +0100] "POST /add HTTP/1.1" 200 268 "https://metube.jerdal.no/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.6594.196 Safari/537.36"
WARNING: [youtube] Sign in to confirm you’re not a bot. Use --cookies-from-browser or --cookies for the authentication. See  https://github.com/yt-dlp/yt-dlp/wiki/FAQ#how-do-i-pass-cookies-to-yt-dlp  for how to manually pass cookies. Also see  https://github.com/yt-dlp/yt-dlp/wiki/Extractors#exporting-youtube-cookies  for tips on effectively exporting YouTube cookies
WARNING: No video formats found!
WARNING: Requested format is not available
ERROR: [youtube] Af-vC8Q8M7c: No video formats found!

**Comment by Trump2028** [comment]
I had this problem before, and it was solved when I switched the VPN's IP address.

**Comment by bobs409** [comment]
No video formats found!   Nothing will download for the past 2 days. ???

**Comment by commodore-84** [comment]
> I had this problem before, and it was solved when I switched the VPN's IP address.

THIS IS THE SOLUTION!!!!

**Comment by jeffv03** [comment]
Hello :)
changing IP ? not using a vpn and have a fixed IP so how to correct this  ?

as I was getting thios error very often, I tried this : took a 144 videos playlist url and used metube to download it all... and almost all of the videos got downloaded fine, but the actual ones that failed alone before still doesn't, and some few others issued error 403, and some random ones doesn't also as it were marked as 'private' ones... randomly (these ones was really not needing to be 'private' ;)

**Comment by PikuZheng** [comment]
> YT to constantly change stuff to prevent downloaders.

thats it
downloading will be interrupted at random percentages, which is a measure by YouTube to resist downloaders. less frequent downloads may help
in addition, the new version of yt-dlp has improvements
on the other hand, the IP of the data center (VPS) or some regional restrictions will cause the download to be interrupted as soon as it starts, which is different from the above
